
language: python
python:
  - "3.4"

cache: pip

install:
  - pip install -r login/requirements/dev.txt

virtualenv:
  system_site_packages: true

stages:
  - check-container
  - test

jobs:
  include:
    - stage: check-container
      sudo: required
      services:
        - docker
      name: "Checking Container Run"
      script:
        - make check-service

    - stage: test
      name: "Unit Tests"
      script: sh run-tests.sh

    
